---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 小凡.
--- DateTime: 2025/8/15 20:14
---


-- 1参数
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. userId

if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

if (redis.call('sismember',orderKey,userId) == 1) then
    return 2
end

redis.call('sadd',orderKey,userId)
redis.call('incrby',stockKey,-1)
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderKey,'id',orderId)
return 0