---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 小凡.
--- DateTime: 2025/8/14 20:34
---

if(redis.call("GET",KEYS[1])==ARGV[1]) then
    return redis.call("DEL",KEYS[1])
end
return 0